### PR TITLE
Update the job-dsl plugin for Pipelines support

### PR DESCRIPTION
**Pull request by pwnage101**
1.47 is the minimum version that supports Pipeline.

### CODE REVIEW

**Comment by pwnage101** [comment]
Testing locally, i discovered the error:

```
SEVERE: Failed Loading plugin Job DSL v1.68 (job-dsl)
java.io.IOException: Job DSL v1.68 failed to load.
 - You must update Jenkins from v2.60.3 to v2.73 or later to run this plugin.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by michaelyoungstrom** [comment]
@pwnage101 I'm currently working on bumping us to 2.89.4 https://github.com/edx/jenkins-configuration/pull/80

**Comment by pwnage101** [comment]
Looks like there's already a PR open to upgrade jenkins to 2.89.4: https://github.com/edx/jenkins-configuration/pull/80

**Comment by michaelyoungstrom** [comment]
We may unfortunately need to hold off on this, as GHPRB is no longer supported on newer versions of the DSL plugin, which means we will need to make a lot of changes to get this working with our existing jobs. We plan on doing it, just not sure when. Is this something that is a major blocker for you?

CC: @estute @jmbowman

**Comment by pwnage101** [comment]
job-dsl 1.60 is the latest release containing GHPRB support.  Since the minimum for Pipeline support is 1.47, we should be good with any job-dsl between 1.47 and 1.60 as far as these two plugins are concerned.

**Comment by pwnage101** [comment]
closed due to https://github.com/edx/jenkins-configuration/pull/84

**Pull request closed without merging**
